const FLAGS: Record<string, string> = {
  "Argentina": "🇦🇷",
  "Australia": "🇦🇺",
  "Austria": "🇦🇹",
  "Belgium": "🇧🇪",
  "Bolivia": "🇧🇴",
  "Brazil": "🇧🇷",
  "Bulgaria": "🇧🇬",
  "Cambodia": "🇰🇭",
  "Canada": "🇨🇦",
  "Chile": "🇨🇱",
  "China": "🇨🇳",
  "Colombia": "🇨🇴",
  "Costa Rica": "🇨🇷",
  "Croatia": "🇭🇷",
  "Czech Republic": "🇨🇿",
  "Ecuador": "🇪🇨",
  "Egypt": "🇪🇬",
  "El Salvador": "🇸🇻",
  "France": "🇫🇷",
  "Germany": "🇩🇪",
  "Greece": "🇬🇷",
  "Guatemala": "🇬🇹",
  "Honduras": "🇭🇳",
  "Hungary": "🇭🇺",
  "India": "🇮🇳",
  "Indonesia": "🇮🇩",
  "Iran": "🇮🇷",
  "Israel": "🇮🇱",
  "Italy": "🇮🇹",
  "Japan": "🇯🇵",
  "Jordan": "🇯🇴",
  "Kazakhstan": "🇰🇿",
  "Kenya": "🇰🇪",
  "Macedonia": "🇲🇰",
  "Malaysia": "🇲🇾",
  "Mexico": "🇲🇽",
  "Morocco": "🇲🇦",
  "Netherlands": "🇳🇱",
  "Nicaragua": "🇳🇮",
  "North Macedonia": "🇲🇰",
  "Pakistan": "🇵🇰",
  "Panama": "🇵🇦",
  "Paraguay": "🇵🇾",
  "Peru": "🇵🇪",
  "Philippines": "🇵🇭",
  "Poland": "🇵🇱",
  "Portugal": "🇵🇹",
  "Romania": "🇷🇴",
  "Serbia": "🇷🇸",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  "Spain": "🇪🇸",
  "Sri Lanka": "🇱🇰",
  "Taiwan": "🇹🇼",
  "Thailand": "🇹🇭",
  "Turkey": "🇹🇷",
  "Türkiye": "🇹🇷",
  "Ukraine": "🇺🇦",
  "United States": "🇺🇸",
  "USA": "🇺🇸",
  "Uruguay": "🇺🇾",
  "Uzbekistan": "🇺🇿",
  "Vietnam": "🇻🇳",
  "Zambia": "🇿🇲",
};

/** Returns the flag emoji for a country name, or empty string if unknown. */
export function countryFlag(country: string): string {
  return FLAGS[country] ?? "";
}

/** Returns "🇨🇱 Chile" or just "Chile" if no flag is known. */
export function countryWithFlag(country: string): string {
  const flag = FLAGS[country];
  return flag ? `${flag} ${country}` : country;
}
